baseURL = "https://speedstar18fct.github.io/"
languageCode = "en-us"
title = "Masahiro Endo"
theme = "hugo-initio"
publishDir = "docs"

[params]
    name = "Masahiro Endo"
    description = "フリーランスのWebエンジニアとして活動しています"
    year = 2018
    avatar = "images/guy.jpg"
    background = ""
    favicon = "images/favicon.png"
    DateForm = "January 2, 2006"

    showSubheader = false
    showServices = true
    showRecentWorks = false
    showDownload = false
    showClients = false

    footerEnableContact = true
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "GA-000000000-0"

[[params.social]]
	title = "facebook"
	url = "https://www.facebook.com/masahiro.endo.77770"
    icon = "fa-facebook-square"
    footer = true
    sharethis = true
    network = "facebook"
[[params.social]]
	title = "twitter"
	url = "https://twitter.com/"
    icon = "fa-twitter-square"
    footer = false
    sharethis = false
    network = "twitter"
[[params.social]]
	title = "instagram"
	url = "https://www.instagram.com/"
    icon = "fa-instagram"
    footer = false
    sharethis = false
    network = ""
[[params.social]]
	title = "google+"
	url = "https://plus.google.com/"
    icon = "fa-google-plus-square"
    footer = false
    sharethis = false
    network = "googleplus"
[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/nickname"
    icon = "fa-linkedin-square"
    footer = false
    sharethis = false
    network = "linkedin"
[[params.social]]
	title = "tumblr"
	url = "https://nickname.tumblr.com"
    icon = "fa-tumblr-square"
    footer = false
    sharethis = false
    network = "tumblr"
[[params.social]]
	title = "github"
	url = "https://github.com/speedstar18fct"
    icon = "fa-github"
    footer = true
    sharethis = true
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:some.email@somewhere.com"
    icon = "fa-envelope"
    footer = false
    sharethis = false
    network = "email"